export const GET_ALL_POKEMONS_PENDING = "GET_ALL_POKEMONS_PENDING";
export const GET_ALL_POKEMONS_SUCCESS = "GET_ALL_POKEMONS_SUCCESS";
export const GET_ALL_POKEMONS_FAILURE = "GET_ALL_POKEMONS_FAILURE";

export const GET_GET_POKEMON_PENDING = "GET_GET_POKEMON_PENDING";
export const GET_GET_POKEMON_SUCCESS = "GET_GET_POKEMON_SUCCESS";
export const GET_GET_POKEMON_FAILURE = "GET_GET_POKEMON_FAILURE";
